name: TotalAdmin
version: '${project.version}'
main: dev.feliperf.plugins.TotalAdmin
api-version: '1.20'
load: STARTUP
authors: [Felipe Ribeiro]
dependencies:
  - org.jetbrains.kotlin:kotlin-stdlib:1.6.10
commands:
  admin:
    description: Activates ADMIN mode for those who have permission to be
    usage: /admin
  noadmin:
    description: Disables ADMIN mode
    usage: /noadmin
  gamemode:
    description: Switch from Gamemode
    usage: /gamemode
  setspawn:
    description: Set server spawn
    usage: /setspawn
  fly:
    description: Allows player fly
    usage: /fly
  timeset:
    description: Changes current user world TimeSet
    usage: /timeset
  kill:
    description: Kills itself or a target Player
    usage: /kill
  warning:
    description: Custom server warning visible to all online players
    usage: /warning
  login:
    description: Authenticate user login in server
    usage: /login
  register:
    description: Authenticate user register in server
    usage: /register